// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDROI_DhKcRbgcxLh9Y7DQzm1wMkzHIMZU',
    appId: '1:62612744678:web:3195a5bc8305617b684e27',
    messagingSenderId: '62612744678',
    projectId: 'flutterfirebasesetup-d4f1b',
    authDomain: 'flutterfirebasesetup-d4f1b.firebaseapp.com',
    storageBucket: 'flutterfirebasesetup-d4f1b.appspot.com',
    measurementId: 'G-PD7WS47VD7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKpeEYn1moNBP-CRo0MQEo22L9wb_Q2B0',
    appId: '1:62612744678:android:bba0be3f4e644290684e27',
    messagingSenderId: '62612744678',
    projectId: 'flutterfirebasesetup-d4f1b',
    storageBucket: 'flutterfirebasesetup-d4f1b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOrp14KUB8ocjN3O54rCZYz2_KfWcYNWs',
    appId: '1:62612744678:ios:26458e28d0a81591684e27',
    messagingSenderId: '62612744678',
    projectId: 'flutterfirebasesetup-d4f1b',
    storageBucket: 'flutterfirebasesetup-d4f1b.appspot.com',
    iosBundleId: 'com.example.communityBuild',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBOrp14KUB8ocjN3O54rCZYz2_KfWcYNWs',
    appId: '1:62612744678:ios:26458e28d0a81591684e27',
    messagingSenderId: '62612744678',
    projectId: 'flutterfirebasesetup-d4f1b',
    storageBucket: 'flutterfirebasesetup-d4f1b.appspot.com',
    iosBundleId: 'com.example.communityBuild',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDROI_DhKcRbgcxLh9Y7DQzm1wMkzHIMZU',
    appId: '1:62612744678:web:ce7850cd48a56553684e27',
    messagingSenderId: '62612744678',
    projectId: 'flutterfirebasesetup-d4f1b',
    authDomain: 'flutterfirebasesetup-d4f1b.firebaseapp.com',
    storageBucket: 'flutterfirebasesetup-d4f1b.appspot.com',
    measurementId: 'G-FGXKVR9J1Y',
  );

}